# Generated by Django 4.1.2 on 2022-12-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
