# Generated by Django 4.1.2 on 2022-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_enquiry_height_enquiry_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
