# Generated by Django 4.1.2 on 2022-12-19 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enquiry_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
