# Generated by Django 4.1.2 on 2022-12-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_body_type_user_exercies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_exercies',
            old_name='Fitness_type',
            new_name='fitness_type',
        ),
    ]
