# Generated by Django 4.1.2 on 2022-12-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_fitness_type_user_exercies_fitness_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_exercies',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='user_exercies',
            name='fitness_type',
        ),
        migrations.DeleteModel(
            name='body_type',
        ),
        migrations.DeleteModel(
            name='User_exercies',
        ),
    ]
