# Generated by Django 4.1.2 on 2022-12-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_body_type_user_exercies'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_type',
            name='abdomen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='ankle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='biceps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='forearm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='knee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='neck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='thigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body_type',
            name='wrist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
