# Generated by Django 4.1.2 on 2022-12-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_body_type_abdomen_body_type_ankle_body_type_biceps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body_type',
            name='weight',
        ),
    ]
