# Generated by Django 4.1.2 on 2022-11-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_trainer_facebook_trainer_pinterest_trainer_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='youtube',
        ),
    ]
