# Generated by Django 4.1.2 on 2022-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_body_type_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_exercises',
            name='description',
        ),
        migrations.AddField(
            model_name='fitness_exercises',
            name='times',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
