# Generated by Django 4.1.2 on 2022-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_fitness_exercises_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_type',
            name='body_type_img',
            field=models.ImageField(blank=True, upload_to='body_type/'),
        ),
    ]
