# Generated by Django 4.1.2 on 2022-12-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_body_type_body_type_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness_type',
            name='body_type_img',
            field=models.ImageField(blank=True, upload_to='fitness_type/'),
        ),
    ]
