# Generated by Django 4.1.2 on 2022-12-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fitness_type_body_type_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitness_type',
            old_name='body_type_img',
            new_name='fitness_type_img',
        ),
    ]
