# Generated by Django 4.1.2 on 2022-11-24 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_notifiuserstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifiUserStatus',
            new_name='NotifUserStatus',
        ),
    ]
