# Generated by Django 4.1.2 on 2022-11-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_assignsubscriber_delete_assignsubscibers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
