# Generated by Django 4.1.2 on 2022-11-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_notiftrainerstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerSubscriberReport',
        ),
    ]
