# Generated by Django 4.1.2 on 2022-11-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_delete_trainersubscriberreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerAchivement',
        ),
    ]
