# Generated by Django 4.1.2 on 2022-12-14 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_remove_enquiry_detail_remove_enquiry_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='user',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
