# Generated by Django 4.1.2 on 2022-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_enquiry_user_enquiry_enquiry_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='abdomen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ankle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='biceps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='forearm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='knee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='neck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='thigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='wrist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
