# Generated by Django 4.1.2 on 2022-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_enquiry_abdomen_enquiry_age_enquiry_ankle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='height',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='today_calories',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='today_training_activity',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='weight',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
