# Generated by Django 4.1.2 on 2022-12-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_enquiry_height_remove_enquiry_send_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness_type',
            fields=[
                ('type_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Fitness type',
            },
        ),
        migrations.CreateModel(
            name='Fitness_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('exercise_img', models.ImageField(upload_to='Fitness_exercises/')),
                ('description', models.TextField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fitness_type')),
            ],
            options={
                'verbose_name_plural': 'Fitness Exercies',
            },
        ),
    ]
