# Generated by Django 4.1.2 on 2022-12-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_enquiry_height_remove_enquiry_send_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitness_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Fitness type',
            },
        ),
    ]
