# Generated by Django 4.1.2 on 2022-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_fitness_type_fitness_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness_exercises',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
