# Generated by Django 4.1.2 on 2022-12-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_fitness_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('exercise_img', models.ImageField(upload_to='Fitness_exercises/')),
                ('description', models.TextField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fitness_type')),
            ],
        ),
    ]
