# Generated by Django 4.1.2 on 2022-12-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_fitness_exercises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitness_exercises',
            options={'verbose_name_plural': 'Fitness Exercies'},
        ),
    ]
