# Generated by Django 4.1.2 on 2022-12-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_fitness_exercises_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_exercises',
            name='type',
        ),
    ]
