# Generated by Django 4.1.2 on 2022-12-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_fitness_exercises_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fitness_exercises',
        ),
    ]
